### ISSUE TITLE
login function does not check validity of password

### ISSUE THREAD

**Issue by JacobHenner** [shreshthkhilani/Stressed-at-Penn#2]
The login function in index.js is not properly checking passwords. Instead of comparing the user's input to the stored password, it's assigning the stored password to the variable which previously stored the user input, and evaluating that expression. This will (almost) always evaluate to true, and allow an adversary to log in.

```
    if (pw = json_data.pw) {
                            req.session.login = true;
                            req.session.user = user;
                            res.send({"success": true});
                        }
```

**Comment by shreshthkhilani** [comment]
Issue fixed! Thanks
